version: "3.7"
services:  
  front-end:
    container_name: reactimage
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    command: npm start